name: Auto Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run docs:build

      - name: Zip the built documentation
        run: |
          cd docs/.vitepress
          zip -r dist.zip dist

      - name: Get current time
        id: time
        run: echo "CURRENT_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.CURRENT_TIME }}
          release_name: Release ${{ env.CURRENT_TIME }}
          body: |
            Release automatically generated by GitHub Actions.
            - Commit: ${{ github.sha }}
            - Timestamp: ${{ env.CURRENT_TIME }}
          draft: false
          prerelease: false

      - name: Upload ZIP file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: docs/.vitepress/dist.zip
          asset_name: dist-${{ env.CURRENT_TIME }}.zip
          asset_content_type: application/zip
