name: Auto Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run docs:build

      - name: Zip the built documentation
        run: |
          cd docs/.vitepress
          zip -r dist.zip dist

      - name: Get current time
        id: time
        run: echo "CURRENT_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          body: 此版本由机器人自动构建
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            docs/.vitepress/dist.zip